### ISSUE TITLE
Mobile UI Issues

### ISSUE THREAD

**Issue by romangg** [anydistro/bxt#103]
Maybe only while sync is running?

![Screenshot_20240717-101203](https://github.com/user-attachments/assets/b88c1458-c7ce-488b-a486-4adcd3307b4e)

**Comment by LordTermor** [comment]
Web is not really supported or tested on mobile, a lot of workflow ways don't really fit there (like dialogs). 

I can make sidebar working on mobile, it's an easy change and most of components are adapted to mobile but I don't really see a reason to use bxt on mobile, you don't typically build packages using your mobile.

**Comment by romangg** [comment]
> but I don't really see a reason to use bxt on mobile, you don't typically build packages using your mobile.

Quickly checking on current state or packages should be possible at least. Changing packages is out of scope.

**Comment by romangg** [comment]
It's also a problem on desktop (here Chrome) when the window is small enough:

![Screenshot_20240719_104634](https://github.com/user-attachments/assets/f2c84733-cacf-4444-a815-d97b8a200bb9)

**Comment by romangg** [comment]
I think we should open separate issues for anything we encounter on mobile. There are not so many I believe.
