### ISSUE TITLE
GitHub deployment is now being skipped

### ISSUE THREAD

**Issue by LordTermor** [anydistro/bxt#104]
After https://github.com/anydistro/bxt/pull/88 the deployment job is being skipped resulting in no updates being applied

**Comment by romangg** [comment]
This one ran the deploy job though: https://github.com/anydistro/bxt/actions/runs/9958067267

Looks like only the tags are not.

**Comment by LordTermor** [comment]
> This one ran the deploy job though: https://github.com/anydistro/bxt/actions/runs/9958067267
> 
> Looks like only the tags are not.

Oh right, then I don't really understand why https://github.com/anydistro/bxt/issues/91 is not fixed on testing instance while I've fixed and it works on my local machine...
