### ISSUE TITLE
Produced ALPM-DB package names are truncated sometimes

### ISSUE THREAD

**Issue by LordTermor** [anydistro/bxt#115]
E.g. resulting autocon instead of autoconf

It might have to do something with the usage of `std::string_view` with underlying C strings.

Took from the log here: #110

**Comment by LordTermor** [comment]
Apparently there's no easy way to reproduce this issue, let's see if it happens with latest updates.

**Comment by LordTermor** [comment]
There was other package where this happened:

`error: multilib database is inconsistent: name mismatch on package lib`

**Comment by romangg** [comment]
So it happens with some unknowm package `lib*` and with `autocon` instead of `autoconf`.

**Comment by LordTermor** [comment]
I've found that actually it happened when I did a full sync locally for the very same `autoconf` and some `lib` package. Good to know it's not something random and potentially easy to debug.
