### ISSUE TITLE
Deployment workflow uses old tag name

### ISSUE THREAD

**Issue by LordTermor** [anydistro/bxt#117]
After https://github.com/anydistro/bxt/pull/88 the tag now is 

https://github.com/anydistro/bxt/blob/f740cf6f0abb5c0c4ac8721e063d548675a5b9a9/.github/workflows/build.yml#L20

while compose file looks for 

https://github.com/anydistro/bxt/blob/f740cf6f0abb5c0c4ac8721e063d548675a5b9a9/docker-compose.yml#L15

causing changes not being applied on deployment

**Comment by romangg** [comment]
I remember we discussed what tag to use in https://github.com/anydistro/bxt/pull/89#pullrequestreview-2171949254. I think that's what it is about and it's unrelated to #88.

Should we switch to bxt_production in line 20?

But how are changes not applied right now? It seems the deployment on the test server is updating regularly.

**Comment by LordTermor** [comment]
> and it's unrelated to https://github.com/anydistro/bxt/pull/88.

Right, it's #89, don't know why I mentioned #88 (maybe because both of them are ci-related)


> Should we switch to bxt_production in line 20?

I'd better use `anydistro/bxt:latest` in https://github.com/anydistro/bxt/blob/f740cf6f0abb5c0c4ac8721e063d548675a5b9a9/docker-compose.yml#L15

as it looks more nice.


> But how are changes not applied right now? It seems the deployment on the test server is updating regularly.

I'm pushing updates manually as I can't test big repository locally.
