### ISSUE TITLE
selection of list view should be remembered

### ISSUE THREAD

**Issue by oberon-manjaro** [anydistro/bxt#122]
when list view is selected on Packages page after any reload or switch to Logs page and back, view will switch back to grid view every time.
I think ones preference should be remembered

**Comment by LordTermor** [comment]
> when list view is selected on Packages page after any reload or switch to Logs page and back, view will switch back to grid view every time. I think ones preference should be remembered

If you are okay, I'd put it as the whole FM state including commits should be remembered
