### ISSUE TITLE
browser window scaling deactivates content

### ISSUE THREAD

**Issue by oberon-manjaro** [anydistro/bxt#123]
as soon as I scale the browser window to half screen or less on my screen, the content is greyed out and dropping content in it will not trigger any action
![image](https://github.com/user-attachments/assets/07001444-ef2c-45b2-9d7c-a89a19210814)
I need to increase window size to slightly more than half screen to activate the content:
![image](https://github.com/user-attachments/assets/2c08270e-bcdc-485d-a01e-c046548a3aba)

**Comment by romangg** [comment]
That's similar to #103, but let's keep both open. The ticket here tracking it for windows being small on desktop and not on mobile alone.
