### ISSUE TITLE
Migrate from CRA

### ISSUE THREAD

**Issue by LordTermor** [anydistro/bxt#4]
The frontend was made using the "Create React App" tool by Facebook which enables an easy first start of the React application. Apparently CRA is not developed anymore and [NextJS](https://nextjs.org/) would be a good alternative. There is a plenty of guides describing the migration process.

**Comment by LordTermor** [comment]
I've decided to go with [Remix](https://github.com/remix-run/remix)

**Comment by romangg** [comment]
> [Remix](https://github.com/remix-run/remix)

Major technology decisions like these should be documented. What are pros and cons to alternatives?

**Comment by LordTermor** [comment]
> > [Remix](https://github.com/remix-run/remix)
> 
> Major technology decisions like these should be documented. What are pros and cons to alternatives?

It's not really major and I already made the initial efforts for the port. Here's a list of pros/cons of remix according to the web resources:

Pros:
- More customizable with less features bundled
- A bit more performant
- Uses less client-side logic, more suitable for applications without a lot of dynamic content (which bxt is)
Cons:
- Less mature community-wise as it's newer


But the most important is that I feel more convenient to work with Remix as it's a react router successor I used to work with and I think it's API a bit cleaner.

**Comment by LordTermor** [comment]
As Remix is mainly a SSR framework and [this](https://github.com/anydistro/bxt/issues/76) concludes current thoughts about SSR usage, I'll dedicate this issue to the migrating away from deprecated Create-React-App to the modern toolchain called [Vite](https://vitejs.dev/) that already was done during the work on Remix port. 

Vite was initially developed for VueJS but now is a great framework-agnostic tool to ease the development of various frameworks apps including React. It's faster than CRA and actively developed.

**Comment by LordTermor** [comment]
Finished with #77
