### ISSUE TITLE
Implement token refreshment

### ISSUE THREAD

**Issue by LordTermor** [anydistro/bxt#54]
Implement token expiration and refreshment in some period of time.

**Comment by fhdk** [comment]
May I suggest using the **Authorization** header of type **Bearer <tokenvalue>**?

May I suggest using returning the token/refresh_token data in the response body with information about issued_at and expires_in or something similar?

As of now one send a urlencoded form with username and password - may I suggest that you add an argument to the form - indicating which type of authentication request - a **grant_type** with value **password** or **refresh_token**?

**Comment by LordTermor** [comment]
While overall my idea with refresh token is roughly the same, I don't think it's a good idea to 

> using the Authorization header of type Bearer ?


As in web you'd need to store token in the local storage which [is more vulnerable to cross-site scripting attacks](https://dev.to/cotter/localstorage-vs-cookies-all-you-need-to-know-about-storing-jwt-tokens-securely-in-the-front-end-15id).

**Comment by LordTermor** [comment]
> indicating which type of authentication request - a grant_type with value password or refresh_token?

It's a part of OAuth 2.0 standard which I don't use now as we don't have any external auth server. It's for sure a room for extension if we want to integrate something like single sign-on but for now I'll implement fairly basic access-refresh tokens model.

**Comment by fhdk** [comment]
I will work with what you decide. I use OAuth standard - using an internal implementation, within the API - selfhosted one could say.

It was merely a suggestion on how to differentiate the methods but you could do that with endpoint.
