### ISSUE TITLE
Use HTTP methods properly

### ISSUE THREAD

**Issue by fhdk** [anydistro/bxt#59]
The user management endpoints is using POST for all actions.

Best practise is to use the relevant verb for the associated action

|verb|action|
|---|---|
|POST | Create |
| GET | Read |
| PUT | Update |
| DELETE | Delete |

**Comment by LordTermor** [comment]
I split your issue into two: https://github.com/anydistro/bxt/issues/60

**Comment by fhdk** [comment]
The difference between PUT and PATCH is the amount of data transferred.

PUT is for the situation where your record is so small you send the complete record.

PATCH is for situations where the complete record is a very large payload and thus does not make sense if you har only changing a small subset of the data. 

The PATCH request is usually used on conjunction with an ETAG header or other means to ensure the data has not been altered between requests. E.g. the GET to read the record and PATCH to send a minor change.

You are using the **username** in the update request path and you are expecting a post body identical to the POST request - thus it is not a PATCH but a PUT updating an existing record.

I know there is different opinions on the matter - so - as long as you are consitent in your approach.

I only point out that the common usage and best practise is the verbs I referenced.

|verb |action|
|---|---|
|POST | Create |
|GET | Read |
| PUT |Update |
| DELETE |Delete |

How one choose to layout the request path should not influence on the VERB used - an update is still a PUT even when you include the ID in the path.

GET /users
GET /users/{{id}}
POST /users
PUT /users/{{id}}
DELETE /users/{{id}}

But you are the main developer and maintainer - your choice ...

When I started working with API it was learning by doing - and I had to refactor a lot of code in that process ... I am hoping my comments - from my experience - will ultimately contribute to your coding :smile:
