### ISSUE TITLE
snap endpoint

### ISSUE THREAD

**Issue by fhdk** [anydistro/bxt#78]
Using postman to test the api - preparing for changes to bxtctl

I did expect an error, so it could be intentional.

Posting to `/api/packages/snap` from one repo to another e.g. unstable/core -> testing/multilib succeeds.

```
{
  "source": {
    "branch": "unstable",
    "repository": "core",
    "architecture": "x86_64"
  },
  "target": {
    "branch": "testing",
    "repository": "multilib",
    "architecture": "x86_64"
  }
}
```
result
```
{
    "status": "ok"
}
```
Same happens cross repo and cross architecture - despite `aarch64` having no multilib repo
```
{
  "source": {
    "branch": "unstable",
    "repository": "core",
    "architecture": "x86_64"
  },
  "target": {
    "branch": "testing",
    "repository": "multilib",
    "architecture": "aarch64"
  }
}
```
result
```
{
    "status": "ok"
}
```

this time unstable/core/x86_64 -> testing/extra/aarch64

```
{
  "source": {
    "branch": "unstable",
    "repository": "core",
    "architecture": "x86_64"
  },
  "target": {
    "branch": "testing",
    "repository": "extra",
    "architecture": "aarch64"
  }
}
```
result
```
{
    "status": "ok"
}
```

**Comment by LordTermor** [comment]
> so it could be intentional.

Exactly, you can snap any sections you want. It doesn't really make sense but this operation is designed to be as generic as possible as there might be other use cases to it.

**Comment by fhdk** [comment]
Thank you for confirming.

I understand the generic use-case.

Closing the issue
