### ISSUE TITLE
packages endpoint - can be forced into 502 Bad Gateway

### ISSUE THREAD

**Issue by fhdk** [anydistro/bxt#98]
By leaving out the value of one parameter the daemon becomes unresponsive 

## Reproduce

```
GET /api/packages?branch=unstable&repository=multilib&architecture=
```

Result after ~2m  a **502 Bad Gateway** is returned

## Expected
Since the parameters are documented to be required - I expected a 400 Bad Request - after the service has validated the parameters.

**Comment by LordTermor** [comment]
This needs validation improvements of course
